# Generated by Django 2.0.1 on 2018-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0002_auto_20180306_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
