# Generated by Django 2.0.2 on 2018-04-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0005_auto_20180327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
