# Generated by Django 2.0.2 on 2018-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0007_auto_20180405_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
