# Generated by Django 2.0.2 on 2018-04-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0008_auto_20180405_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
