# Generated by Django 2.0.2 on 2018-04-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0009_auto_20180405_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.CharField(max_length=50),
        ),
    ]
