# Generated by Django 2.0.2 on 2018-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0012_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
